# Predicting Football Match Outcomes Across Europe's Top Leagues Using Machine Learning Classification Models

## Add python libraries to analysis

In [81]:
import pandas as pd
import seaborn as sns
%matplotlib inline  
import matplotlib.pyplot as plt
import numpy as np

## Create a Function for reading in the 6 csv files
#### The function will also:
#### Rename columns
#### Create duplicate dataframe with required columns only
#### Create new columns for half time and full time goals
#### Create a Dictionary to replace League names from the csv files.  
#### The purpose of this is to stop code duplication

In [82]:
def prepare_league(file_name): # file_name is a parameter given to the function
    
    # read in csv
    df = pd.read_csv(file_name)
    
    # rename columns
    df = df.rename(columns={
    "Div": "League",
    "HomeTeam": "Home_Team",
    "AwayTeam": "Away_Team",
    "FTHG": "FT_Home_Goals",
    "FTAG": "FT_Away_Goals",
    "FTR": "Result",
    "HTHG": "HT_Home_Goals",
    "HTAG": "HT_Away_Goals",
    "HST": "Home_Shots_On_Target",
    "AST": "Away_Shots_On_Target",
    } 
    )
    
    # create duplicate dataframe with required columns only
    df = df[
        ["Date", 
         "League", 
          "Home_Team", 
          "Away_Team", 
          "HT_Home_Goals",
          "HT_Away_Goals", 
          "FT_Home_Goals", 
          "FT_Away_Goals", 
          "Result"] 
    ].copy()
    
    # create new columns for half time and full time goals
    df["HT_Goals"] = (
    df["HT_Home_Goals"] + df["HT_Away_Goals"] 
    )

    df["FT_Goals"] = (
    df["FT_Home_Goals"] + df["FT_Away_Goals"] 
    )

    # Create a Dictionary to replace League names from the csv files.  This will make it more readable once i created a merged dataframe
    df["League"] = df["League"].replace( 
        {
            "D1": "German Bundesliga",
            "E0": "English Premier League",
            "E1": "English Championship",
            "SP1": "Spanish La Liga",
            "I1": "Italian Serie A",
            "F1": "French Ligue 1",
        }
    )
            

    return df

## Data Preparation For Bundesliga File

## 1 CSV = Load the Bundesliga Master File

## Call the prepare_league function

In [83]:
df_Bundesliga = prepare_league("Bundesliga_Master.csv")

In [84]:
df_Bundesliga.head(5)

,Date,League,Home_Team,Away_Team,HT_Home_Goals,HT_Away_Goals,FT_Home_Goals,FT_Away_Goals,Result,HT_Goals,FT_Goals
0,22/08/2014,German Bundesliga,Bayern Munich,Wolfsburg,1.0,0.0,2,1,H,1.0,3
1,23/08/2014,German Bundesliga,Dortmund,Leverkusen,0.0,1.0,0,2,A,1.0,2
2,23/08/2014,German Bundesliga,Ein Frankfurt,Freiburg,1.0,0.0,1,0,H,1.0,1
3,23/08/2014,German Bundesliga,FC Koln,Hamburg,0.0,0.0,0,0,D,0.0,0
4,23/08/2014,German Bundesliga,Hannover,Schalke 04,0.0,0.0,2,1,H,0.0,3

In [85]:
df_Bundesliga.tail(5)

,Date,League,Home_Team,Away_Team,HT_Home_Goals,HT_Away_Goals,FT_Home_Goals,FT_Away_Goals,Result,HT_Goals,FT_Goals
3667,17/05/2025,German Bundesliga,Hoffenheim,Bayern Munich,0.0,1.0,0,4,A,1.0,4
3668,17/05/2025,German Bundesliga,Mainz,Leverkusen,1.0,0.0,2,2,D,1.0,4
3669,17/05/2025,German Bundesliga,M'gladbach,Wolfsburg,0.0,0.0,0,1,A,0.0,1
3670,17/05/2025,German Bundesliga,RB Leipzig,Stuttgart,2.0,1.0,2,3,A,3.0,5
3671,17/05/2025,German Bundesliga,St Pauli,Bochum,0.0,1.0,0,2,A,1.0,2

In [86]:
df_Bundesliga.shape

(3672, 11)

In [87]:
df_Bundesliga.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3672 entries, 0 to 3671
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           3672 non-null   object
 1   League         3672 non-null   object
 2   Home_Team      3672 non-null   object
 3   Away_Team      3672 non-null   object
 4   HT_Home_Goals  3671 non-null   float64
 5   HT_Away_Goals  3671 non-null   float64
 6   FT_Home_Goals  3672 non-null   int64
 7   FT_Away_Goals  3672 non-null   int64
 8   Result         3672 non-null   object
 9   HT_Goals       3671 non-null   float64
 10  FT_Goals       3672 non-null   int64
dtypes: float64(3), int64(3), object(5)
memory usage: 315.7+ KB

In [88]:
df_Bundesliga.isnull().sum()

Date             0
League           0
Home_Team        0
Away_Team        0
HT_Home_Goals    1
HT_Away_Goals    1
FT_Home_Goals    0
FT_Away_Goals    0
Result           0
HT_Goals         1
FT_Goals         0
dtype: int64

### Find the isnull values listed above

In [89]:
df_Bundesliga[df_Bundesliga['HT_Home_Goals'].isna()]

,Date,League,Home_Team,Away_Team,HT_Home_Goals,HT_Away_Goals,FT_Home_Goals,FT_Away_Goals,Result,HT_Goals,FT_Goals
3487,14/12/2024,German Bundesliga,Union Berlin,Bochum,NaN,NaN,0,2,A,NaN,2

### Three missing values relating to half time statistics were identified for the Bundesliga fixture Union Berlin vs Bochum (14 December 2024)
### The match was abandoned due to spectator interruptions and Bochum was awarded the game 0-2

In [90]:
df_Bundesliga = df_Bundesliga.dropna()

In [91]:
df_Bundesliga.isnull().sum()

Date             0
League           0
Home_Team        0
Away_Team        0
HT_Home_Goals    0
HT_Away_Goals    0
FT_Home_Goals    0
FT_Away_Goals    0
Result           0
HT_Goals         0
FT_Goals         0
dtype: int64

In [92]:
df_Bundesliga.tail(5)

,Date,League,Home_Team,Away_Team,HT_Home_Goals,HT_Away_Goals,FT_Home_Goals,FT_Away_Goals,Result,HT_Goals,FT_Goals
3667,17/05/2025,German Bundesliga,Hoffenheim,Bayern Munich,0.0,1.0,0,4,A,1.0,4
3668,17/05/2025,German Bundesliga,Mainz,Leverkusen,1.0,0.0,2,2,D,1.0,4
3669,17/05/2025,German Bundesliga,M'gladbach,Wolfsburg,0.0,0.0,0,1,A,0.0,1
3670,17/05/2025,German Bundesliga,RB Leipzig,Stuttgart,2.0,1.0,2,3,A,3.0,5
3671,17/05/2025,German Bundesliga,St Pauli,Bochum,0.0,1.0,0,2,A,1.0,2

### Check Home_Team and Away_Team columns in case of duplicate naming, ie FC Koln being also listed as FC Cologne

In [93]:
sorted(df_Bundesliga["Home_Team"].unique() )

['Augsburg',
 'Bayern Munich',
 'Bielefeld',
 'Bochum',
 'Darmstadt',
 'Dortmund',
 'Ein Frankfurt',
 'FC Koln',
 'Fortuna Dusseldorf',
 'Freiburg',
 'Greuther Furth',
 'Hamburg',
 'Hannover',
 'Heidenheim',
 'Hertha',
 'Hoffenheim',
 'Holstein Kiel',
 'Ingolstadt',
 'Leverkusen',
 "M'gladbach",
 'Mainz',
 'Nurnberg',
 'Paderborn',
 'RB Leipzig',
 'Schalke 04',
 'St Pauli',
 'Stuttgart',
 'Union Berlin',
 'Werder Bremen',
 'Wolfsburg']

In [94]:
sorted(df_Bundesliga["Away_Team"].unique() )

['Augsburg',
 'Bayern Munich',
 'Bielefeld',
 'Bochum',
 'Darmstadt',
 'Dortmund',
 'Ein Frankfurt',
 'FC Koln',
 'Fortuna Dusseldorf',
 'Freiburg',
 'Greuther Furth',
 'Hamburg',
 'Hannover',
 'Heidenheim',
 'Hertha',
 'Hoffenheim',
 'Holstein Kiel',
 'Ingolstadt',
 'Leverkusen',
 "M'gladbach",
 'Mainz',
 'Nurnberg',
 'Paderborn',
 'RB Leipzig',
 'Schalke 04',
 'St Pauli',
 'Stuttgart',
 'Union Berlin',
 'Werder Bremen',
 'Wolfsburg']

## No issues discovered with Team names in Bundesliga

## 2 CSV = Load the Premier League Master File

## Call the prepare_league function

In [95]:
df_Premier = prepare_league("Premier_League_Master.csv")

In [96]:
df_Premier.head(5)

,Date,League,Home_Team,Away_Team,HT_Home_Goals,HT_Away_Goals,FT_Home_Goals,FT_Away_Goals,Result,HT_Goals,FT_Goals
0,20/09/2014,English Premier League,Aston Villa,Arsenal,0,3,0,3,A,3,3
1,20/09/2014,English Premier League,Burnley,Sunderland,0,0,0,0,D,0,0
2,20/09/2014,English Premier League,Newcastle,Hull,0,0,2,2,D,0,4
3,20/09/2014,English Premier League,QPR,Stoke,1,1,2,2,D,2,4
4,20/09/2014,English Premier League,West Ham,Liverpool,2,1,3,1,H,3,4

In [97]:
df_Premier.tail(5)

,Date,League,Home_Team,Away_Team,HT_Home_Goals,HT_Away_Goals,FT_Home_Goals,FT_Away_Goals,Result,HT_Goals,FT_Goals
4555,25/05/2025,English Premier League,Newcastle,Everton,0,0,0,1,A,0,1
4556,25/05/2025,English Premier League,Nott'm Forest,Chelsea,0,0,0,1,A,0,1
4557,25/05/2025,English Premier League,Southampton,Arsenal,0,1,1,2,A,1,3
4558,25/05/2025,English Premier League,Tottenham,Brighton,1,0,1,4,A,1,5
4559,25/05/2025,English Premier League,Wolves,Brentford,0,1,1,1,D,1,2

In [98]:
df_Premier.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4560 entries, 0 to 4559
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           4560 non-null   object
 1   League         4560 non-null   object
 2   Home_Team      4560 non-null   object
 3   Away_Team      4560 non-null   object
 4   HT_Home_Goals  4560 non-null   int64
 5   HT_Away_Goals  4560 non-null   int64
 6   FT_Home_Goals  4560 non-null   int64
 7   FT_Away_Goals  4560 non-null   int64
 8   Result         4560 non-null   object
 9   HT_Goals       4560 non-null   int64
 10  FT_Goals       4560 non-null   int64
dtypes: int64(6), object(5)
memory usage: 392.0+ KB

In [99]:
df_Premier.shape

(4560, 11)

In [100]:
df_Premier.isnull().sum()

Date             0
League           0
Home_Team        0
Away_Team        0
HT_Home_Goals    0
HT_Away_Goals    0
FT_Home_Goals    0
FT_Away_Goals    0
Result           0
HT_Goals         0
FT_Goals         0
dtype: int64

In [101]:
### Check Home_Team and Away_Team columns in case of duplicate naming, ie Nottm Forest being also listed as Nottingham Forest

In [102]:
sorted(df_Premier["Home_Team"].unique() )

['Arsenal',
 'Aston Villa',
 'Bournemouth',
 'Brentford',
 'Brighton',
 'Burnley',
 'Cardiff',
 'Chelsea',
 'Crystal Palace',
 'Everton',
 'Fulham',
 'Huddersfield',
 'Hull',
 'Ipswich',
 'Leeds',
 'Leicester',
 'Liverpool',
 'Luton',
 'Man City',
 'Man United',
 'Middlesbrough',
 'Newcastle',
 'Norwich',
 "Nott'm Forest",
 'QPR',
 'Sheffield United',
 'Southampton',
 'Stoke',
 'Sunderland',
 'Swansea',
 'Tottenham',
 'Watford',
 'West Brom',
 'West Ham',
 'Wolves']

In [103]:
sorted(df_Premier["Away_Team"].unique() )

['Arsenal',
 'Aston Villa',
 'Bournemouth',
 'Brentford',
 'Brighton',
 'Burnley',
 'Cardiff',
 'Chelsea',
 'Crystal Palace',
 'Everton',
 'Fulham',
 'Huddersfield',
 'Hull',
 'Ipswich',
 'Leeds',
 'Leicester',
 'Liverpool',
 'Luton',
 'Man City',
 'Man United',
 'Middlesbrough',
 'Newcastle',
 'Norwich',
 "Nott'm Forest",
 'QPR',
 'Sheffield United',
 'Southampton',
 'Stoke',
 'Sunderland',
 'Swansea',
 'Tottenham',
 'Watford',
 'West Brom',
 'West Ham',
 'Wolves']

## No issues discovered with Team names in Premier League

## 3 CSV = Load the English Championship Master File

## Call the prepare_league function

In [104]:
df_Championship = prepare_league("Championship_Master.csv")

In [105]:
df_Championship.head(5)

,Date,League,Home_Team,Away_Team,HT_Home_Goals,HT_Away_Goals,FT_Home_Goals,FT_Away_Goals,Result,HT_Goals,FT_Goals
0,20/09/2014,English Championship,Brighton,Blackpool,0.0,0.0,0,0,D,0.0,0
1,20/09/2014,English Championship,Derby,Cardiff,0.0,0.0,2,2,D,0.0,4
2,20/09/2014,English Championship,Millwall,Nott'm Forest,0.0,0.0,0,0,D,0.0,0
3,20/09/2014,English Championship,Norwich,Birmingham,0.0,2.0,2,2,D,2.0,4
4,20/09/2014,English Championship,Rotherham,Charlton,0.0,1.0,1,1,D,1.0,2

In [106]:
df_Championship.tail(5)

,Date,League,Home_Team,Away_Team,HT_Home_Goals,HT_Away_Goals,FT_Home_Goals,FT_Away_Goals,Result,HT_Goals,FT_Goals
6619,03/05/2025,English Championship,Sheffield United,Blackburn,0.0,0.0,1,1,D,0.0,2
6620,03/05/2025,English Championship,Sunderland,QPR,0.0,1.0,0,1,A,1.0,1
6621,03/05/2025,English Championship,Swansea,Oxford,1.0,1.0,3,3,D,2.0,6
6622,03/05/2025,English Championship,Watford,Sheffield Weds,1.0,1.0,1,1,D,2.0,2
6623,03/05/2025,English Championship,West Brom,Luton,3.0,1.0,5,3,H,4.0,8

In [107]:
df_Championship.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6624 entries, 0 to 6623
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           6624 non-null   object
 1   League         6624 non-null   object
 2   Home_Team      6624 non-null   object
 3   Away_Team      6624 non-null   object
 4   HT_Home_Goals  6623 non-null   float64
 5   HT_Away_Goals  6623 non-null   float64
 6   FT_Home_Goals  6624 non-null   int64
 7   FT_Away_Goals  6624 non-null   int64
 8   Result         6624 non-null   object
 9   HT_Goals       6623 non-null   float64
 10  FT_Goals       6624 non-null   int64
dtypes: float64(3), int64(3), object(5)
memory usage: 569.4+ KB

In [108]:
df_Championship.shape

(6624, 11)

In [109]:
df_Championship.isnull().sum()

Date             0
League           0
Home_Team        0
Away_Team        0
HT_Home_Goals    1
HT_Away_Goals    1
FT_Home_Goals    0
FT_Away_Goals    0
Result           0
HT_Goals         1
FT_Goals         0
dtype: int64

### Find the isnull values listed above

In [110]:
df_Championship[df_Championship['HT_Home_Goals'].isna()]

,Date,League,Home_Team,Away_Team,HT_Home_Goals,HT_Away_Goals,FT_Home_Goals,FT_Away_Goals,Result,HT_Goals,FT_Goals
5432,27/04/2019,English Championship,Bolton,Brentford,NaN,NaN,0,1,A,NaN,1

### Above game was cancelled and Brentford were awarded the game 0-1. Remove game

In [111]:
df_Championship = df_Championship.dropna()

In [112]:
df_Championship.isnull().sum()

Date             0
League           0
Home_Team        0
Away_Team        0
HT_Home_Goals    0
HT_Away_Goals    0
FT_Home_Goals    0
FT_Away_Goals    0
Result           0
HT_Goals         0
FT_Goals         0
dtype: int64

### Check Home_Team and Away_Team columns in case of duplicate naming, ie Nottm Forest being also listed as Nottingham Forest

In [113]:
sorted(df_Championship["Home_Team"].unique() )

['Aston Villa',
 'Barnsley',
 'Birmingham',
 'Blackburn',
 'Blackpool',
 'Bolton',
 'Bournemouth',
 'Brentford',
 'Brighton',
 'Bristol City',
 'Burnley',
 'Burton',
 'Cardiff',
 'Charlton',
 'Coventry',
 'Derby',
 'Fulham',
 'Huddersfield',
 'Hull',
 'Ipswich',
 'Leeds',
 'Leicester',
 'Luton',
 'Middlesbrough',
 'Millwall',
 'Milton Keynes Dons',
 'Newcastle',
 'Norwich',
 "Nott'm Forest",
 'Oxford',
 'Peterboro',
 'Plymouth',
 'Portsmouth',
 'Preston',
 'QPR',
 'Reading',
 'Rotherham',
 'Sheffield United',
 'Sheffield Weds',
 'Southampton',
 'Stoke',
 'Sunderland',
 'Swansea',
 'Watford',
 'West Brom',
 'Wigan',
 'Wolves',
 'Wrexham',
 'Wycombe']

In [114]:
sorted(df_Championship["Away_Team"].unique() )

['Aston Villa',
 'Barnsley',
 'Birmingham',
 'Blackburn',
 'Blackpool',
 'Bolton',
 'Bournemouth',
 'Brentford',
 'Brighton',
 'Bristol City',
 'Burnley',
 'Burton',
 'Cardiff',
 'Charlton',
 'Coventry',
 'Derby',
 'Fulham',
 'Huddersfield',
 'Hull',
 'Ipswich',
 'Leeds',
 'Leicester',
 'Luton',
 'Middlesbrough',
 'Millwall',
 'Milton Keynes Dons',
 'Newcastle',
 'Norwich',
 "Nott'm Forest",
 'Oxford',
 'Peterboro',
 'Plymouth',
 'Portsmouth',
 'Preston',
 'QPR',
 'Reading',
 'Rotherham',
 'Sheffield United',
 'Sheffield Weds',
 'Southampton',
 'Stoke',
 'Sunderland',
 'Swansea',
 'Watford',
 'West Brom',
 'Wigan',
 'Wolves',
 'Wrexham',
 'Wycombe']

## No issues discovered with Team names in the English Championship

## 4 CSV = Load the Spanish La Liga Master File

## Call the prepare_league function

In [115]:
df_LaLiga = prepare_league("La_Liga_Master.csv")

In [116]:
df_LaLiga.head(5)

,Date,League,Home_Team,Away_Team,HT_Home_Goals,HT_Away_Goals,FT_Home_Goals,FT_Away_Goals,Result,HT_Goals,FT_Goals
0,15/09/2014,Spanish La Liga,Eibar,La Coruna,0,1,0,1,A,1,1
1,19/09/2014,Spanish La Liga,Elche,Eibar,0,2,0,2,A,2,2
2,20/09/2014,Spanish La Liga,Ath Bilbao,Granada,0,1,0,1,A,1,1
3,20/09/2014,Spanish La Liga,Ath Madrid,Celta,2,1,2,2,D,3,4
4,20/09/2014,Spanish La Liga,Espanol,Malaga,1,0,2,2,D,1,4

In [117]:
df_LaLiga.tail(5)

,Date,League,Home_Team,Away_Team,HT_Home_Goals,HT_Away_Goals,FT_Home_Goals,FT_Away_Goals,Result,HT_Goals,FT_Goals
4555,24/05/2025,Spanish La Liga,Getafe,Celta,1,1,1,2,A,2,3
4556,24/05/2025,Spanish La Liga,Vallecano,Mallorca,0,0,0,0,D,0,0
4557,25/05/2025,Spanish La Liga,Girona,Ath Madrid,0,0,0,4,A,0,4
4558,25/05/2025,Spanish La Liga,Villarreal,Sevilla,3,1,4,2,H,4,6
4559,25/05/2025,Spanish La Liga,Ath Bilbao,Barcelona,0,2,0,3,A,2,3

In [118]:
df_LaLiga.shape

(4560, 11)

In [119]:
df_LaLiga.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4560 entries, 0 to 4559
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           4560 non-null   object
 1   League         4560 non-null   object
 2   Home_Team      4560 non-null   object
 3   Away_Team      4560 non-null   object
 4   HT_Home_Goals  4560 non-null   int64
 5   HT_Away_Goals  4560 non-null   int64
 6   FT_Home_Goals  4560 non-null   int64
 7   FT_Away_Goals  4560 non-null   int64
 8   Result         4560 non-null   object
 9   HT_Goals       4560 non-null   int64
 10  FT_Goals       4560 non-null   int64
dtypes: int64(6), object(5)
memory usage: 392.0+ KB

In [120]:
df_LaLiga.isnull().sum()

Date             0
League           0
Home_Team        0
Away_Team        0
HT_Home_Goals    0
HT_Away_Goals    0
FT_Home_Goals    0
FT_Away_Goals    0
Result           0
HT_Goals         0
FT_Goals         0
dtype: int64

In [121]:
### Check Home_Team and Away_Team columns in case of duplicate naming, ie Ath MAdrid being also listed as Atletico Madrid

In [122]:
sorted(df_LaLiga["Home_Team"].unique() )

['Alaves',
 'Almeria',
 'Ath Bilbao',
 'Ath Madrid',
 'Barcelona',
 'Betis',
 'Cadiz',
 'Celta',
 'Cordoba',
 'Eibar',
 'Elche',
 'Espanol',
 'Getafe',
 'Girona',
 'Granada',
 'Huesca',
 'La Coruna',
 'Las Palmas',
 'Leganes',
 'Levante',
 'Malaga',
 'Mallorca',
 'Osasuna',
 'Oviedo',
 'Real Madrid',
 'Sevilla',
 'Sociedad',
 'Sp Gijon',
 'Valencia',
 'Valladolid',
 'Vallecano',
 'Villarreal']

In [123]:
sorted(df_LaLiga["Away_Team"].unique() )

['Alaves',
 'Almeria',
 'Ath Bilbao',
 'Ath Madrid',
 'Barcelona',
 'Betis',
 'Cadiz',
 'Celta',
 'Cordoba',
 'Eibar',
 'Elche',
 'Espanol',
 'Getafe',
 'Girona',
 'Granada',
 'Huesca',
 'La Coruna',
 'Las Palmas',
 'Leganes',
 'Levante',
 'Malaga',
 'Mallorca',
 'Osasuna',
 'Oviedo',
 'Real Madrid',
 'Sevilla',
 'Sociedad',
 'Sp Gijon',
 'Valencia',
 'Valladolid',
 'Vallecano',
 'Villarreal']

## No issues discovered with Team names in the Spanish La Liga

## 5 CSV = Load the Italian Serie A Master File

## Call the prepare_league function

In [124]:
df_SerieA = prepare_league("Serie_A_Master.csv")

In [125]:
df_SerieA.head(5)

,Date,League,Home_Team,Away_Team,HT_Home_Goals,HT_Away_Goals,FT_Home_Goals,FT_Away_Goals,Result,HT_Goals,FT_Goals
0,15/09/2014,Italian Serie A,Verona,Palermo,1.0,1.0,2,1,H,2.0,3
1,20/09/2014,Italian Serie A,Cesena,Empoli,2.0,0.0,2,2,D,2.0,4
2,20/09/2014,Italian Serie A,Milan,Juventus,0.0,0.0,0,1,A,0.0,1
3,21/09/2014,Italian Serie A,Atalanta,Fiorentina,0.0,0.0,0,1,A,0.0,1
4,21/09/2014,Italian Serie A,Chievo,Parma,1.0,0.0,2,3,A,1.0,5

In [126]:
df_SerieA.tail(5)

,Date,League,Home_Team,Away_Team,HT_Home_Goals,HT_Away_Goals,FT_Home_Goals,FT_Away_Goals,Result,HT_Goals,FT_Goals
4555,25/05/2025,Italian Serie A,Empoli,Verona,1.0,1.0,1,2,A,2.0,3
4556,25/05/2025,Italian Serie A,Lazio,Lecce,0.0,1.0,0,1,A,1.0,1
4557,25/05/2025,Italian Serie A,Torino,Roma,0.0,1.0,0,2,A,1.0,2
4558,25/05/2025,Italian Serie A,Udinese,Fiorentina,1.0,0.0,2,3,A,1.0,5
4559,25/05/2025,Italian Serie A,Venezia,Juventus,1.0,2.0,2,3,A,3.0,5

In [127]:
df_SerieA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4560 entries, 0 to 4559
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           4560 non-null   object
 1   League         4560 non-null   object
 2   Home_Team      4560 non-null   object
 3   Away_Team      4560 non-null   object
 4   HT_Home_Goals  4559 non-null   float64
 5   HT_Away_Goals  4559 non-null   float64
 6   FT_Home_Goals  4560 non-null   int64
 7   FT_Away_Goals  4560 non-null   int64
 8   Result         4560 non-null   object
 9   HT_Goals       4559 non-null   float64
 10  FT_Goals       4560 non-null   int64
dtypes: float64(3), int64(3), object(5)
memory usage: 392.0+ KB

In [128]:
df_SerieA.shape

(4560, 11)

In [129]:
df_SerieA.isnull().sum()

Date             0
League           0
Home_Team        0
Away_Team        0
HT_Home_Goals    1
HT_Away_Goals    1
FT_Home_Goals    0
FT_Away_Goals    0
Result           0
HT_Goals         1
FT_Goals         0
dtype: int64

### Find the isnull values listed above

In [130]:
df_SerieA[df_SerieA['HT_Home_Goals'].isna()]

,Date,League,Home_Team,Away_Team,HT_Home_Goals,HT_Away_Goals,FT_Home_Goals,FT_Away_Goals,Result,HT_Goals,FT_Goals
654,28/08/2016,Italian Serie A,Sassuolo,Pescara,NaN,NaN,0,3,A,NaN,3

### The above Italian Serie A game was Sassuolo 2-1 Pescara but recorded as 0-3.  I will also drop this game form the statistics

In [131]:
df_SerieA = df_SerieA.dropna()

In [132]:
df_SerieA.isnull().sum()

Date             0
League           0
Home_Team        0
Away_Team        0
HT_Home_Goals    0
HT_Away_Goals    0
FT_Home_Goals    0
FT_Away_Goals    0
Result           0
HT_Goals         0
FT_Goals         0
dtype: int64

### Check Home_Team and Away_Team columns in case of duplicate naming, ie Inter also listed as Inter Milan

In [133]:
sorted(df_SerieA["Home_Team"].unique() )

['Atalanta',
 'Benevento',
 'Bologna',
 'Brescia',
 'Cagliari',
 'Carpi',
 'Cesena',
 'Chievo',
 'Como',
 'Cremonese',
 'Crotone',
 'Empoli',
 'Fiorentina',
 'Frosinone',
 'Genoa',
 'Inter',
 'Juventus',
 'Lazio',
 'Lecce',
 'Milan',
 'Monza',
 'Napoli',
 'Palermo',
 'Parma',
 'Pescara',
 'Pisa',
 'Roma',
 'Salernitana',
 'Sampdoria',
 'Sassuolo',
 'Spal',
 'Spezia',
 'Torino',
 'Udinese',
 'Venezia',
 'Verona']

In [134]:
sorted(df_SerieA["Home_Team"].unique() )

['Atalanta',
 'Benevento',
 'Bologna',
 'Brescia',
 'Cagliari',
 'Carpi',
 'Cesena',
 'Chievo',
 'Como',
 'Cremonese',
 'Crotone',
 'Empoli',
 'Fiorentina',
 'Frosinone',
 'Genoa',
 'Inter',
 'Juventus',
 'Lazio',
 'Lecce',
 'Milan',
 'Monza',
 'Napoli',
 'Palermo',
 'Parma',
 'Pescara',
 'Pisa',
 'Roma',
 'Salernitana',
 'Sampdoria',
 'Sassuolo',
 'Spal',
 'Spezia',
 'Torino',
 'Udinese',
 'Venezia',
 'Verona']

## No issues discovered with Team names in the Italian Serie A

In [135]:
## 6 CSV = Load the French Ligue 1 Master File

## Call the prepare_league function

In [136]:
df_Ligue1 = prepare_league("Ligue_1_Master.csv")

In [137]:
df_Ligue1.head(5)

,Date,League,Home_Team,Away_Team,HT_Home_Goals,HT_Away_Goals,FT_Home_Goals,FT_Away_Goals,Result,HT_Goals,FT_Goals
0,09/08/2014,French Ligue 1,Nice,Toulouse,1.0,2.0,3,2,H,3.0,5
1,19/09/2014,French Ligue 1,Bordeaux,Evian Thonon Gaillard,1.0,0.0,2,1,H,1.0,3
2,20/09/2014,French Ligue 1,Lorient,Reims,0.0,0.0,0,1,A,0.0,1
3,20/09/2014,French Ligue 1,Marseille,Rennes,0.0,0.0,3,0,H,0.0,3
4,20/09/2014,French Ligue 1,Metz,Bastia,1.0,1.0,3,1,H,2.0,4

In [138]:
df_Ligue1.tail(5)

,Date,League,Home_Team,Away_Team,HT_Home_Goals,HT_Away_Goals,FT_Home_Goals,FT_Away_Goals,Result,HT_Goals,FT_Goals
4232,17/05/2025,French Ligue 1,Nantes,Montpellier,2.0,0.0,3,0,H,2.0,3
4233,17/05/2025,French Ligue 1,Nice,Brest,3.0,0.0,6,0,H,3.0,6
4234,17/05/2025,French Ligue 1,Paris SG,Auxerre,0.0,1.0,3,1,H,1.0,4
4235,17/05/2025,French Ligue 1,St Etienne,Toulouse,1.0,2.0,2,3,A,3.0,5
4236,17/05/2025,French Ligue 1,Strasbourg,Le Havre,1.0,1.0,2,3,A,2.0,5

In [139]:
df_Ligue1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4237 entries, 0 to 4236
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           4237 non-null   object
 1   League         4237 non-null   object
 2   Home_Team      4237 non-null   object
 3   Away_Team      4237 non-null   object
 4   HT_Home_Goals  4236 non-null   float64
 5   HT_Away_Goals  4236 non-null   float64
 6   FT_Home_Goals  4237 non-null   int64
 7   FT_Away_Goals  4237 non-null   int64
 8   Result         4237 non-null   object
 9   HT_Goals       4236 non-null   float64
 10  FT_Goals       4237 non-null   int64
dtypes: float64(3), int64(3), object(5)
memory usage: 364.2+ KB

In [140]:
df_Ligue1.shape

(4237, 11)

In [141]:
df_Ligue1.isnull().sum()

Date             0
League           0
Home_Team        0
Away_Team        0
HT_Home_Goals    1
HT_Away_Goals    1
FT_Home_Goals    0
FT_Away_Goals    0
Result           0
HT_Goals         1
FT_Goals         0
dtype: int64

### Find the isnull values listed above

In [142]:
df_Ligue1[df_Ligue1['HT_Home_Goals'].isna()]

,Date,League,Home_Team,Away_Team,HT_Home_Goals,HT_Away_Goals,FT_Home_Goals,FT_Away_Goals,Result,HT_Goals,FT_Goals
1036,16/04/2017,French Ligue 1,Bastia,Lyon,NaN,NaN,0,3,A,NaN,3

### The above game was abandoned due to pitch invasion and was recorded as 0-0
### I will also drop this fixture

In [143]:
df_Ligue1 = df_Ligue1.dropna()

In [144]:
df_Ligue1.isnull().sum()

Date             0
League           0
Home_Team        0
Away_Team        0
HT_Home_Goals    0
HT_Away_Goals    0
FT_Home_Goals    0
FT_Away_Goals    0
Result           0
HT_Goals         0
FT_Goals         0
dtype: int64

In [145]:
sorted(df_Ligue1["Home_Team"].unique() )

['Ajaccio',
 'Ajaccio GFCO',
 'Amiens',
 'Angers',
 'Auxerre',
 'Bastia',
 'Bordeaux',
 'Brest',
 'Caen',
 'Clermont',
 'Dijon',
 'Evian Thonon Gaillard',
 'Guingamp',
 'Le Havre',
 'Lens',
 'Lille',
 'Lorient',
 'Lyon',
 'Marseille',
 'Metz',
 'Monaco',
 'Montpellier',
 'Nancy',
 'Nantes',
 'Nice',
 'Nimes',
 'Paris FC',
 'Paris SG',
 'Reims',
 'Rennes',
 'St Etienne',
 'Strasbourg',
 'Toulouse',
 'Troyes']

#### Ajaccio GFCO is also known as Gazelec FC Ajaccio
#### Ajaccio is also known as AC Accio
#### They are 2 separate clubs

In [146]:
sorted(df_Ligue1["Away_Team"].unique() )

['Ajaccio',
 'Ajaccio GFCO',
 'Amiens',
 'Angers',
 'Auxerre',
 'Bastia',
 'Bordeaux',
 'Brest',
 'Caen',
 'Clermont',
 'Dijon',
 'Evian Thonon Gaillard',
 'Guingamp',
 'Le Havre',
 'Lens',
 'Lille',
 'Lorient',
 'Lyon',
 'Marseille',
 'Metz',
 'Monaco',
 'Montpellier',
 'Nancy',
 'Nantes',
 'Nice',
 'Nimes',
 'Paris FC',
 'Paris SG',
 'Reims',
 'Rennes',
 'St Etienne',
 'Strasbourg',
 'Toulouse',
 'Troyes']

## No issues discovered with Team names in the French Ligue 1
#### Paris Fc and Paris SG (Also known as PSG) are also 2 separate clubs
#### Who also have adjacent stadiums